### ISSUE TITLE
probleme in release mode

### ISSUE THREAD

**Issue by dongosiddik** [sodipto/flutter-phone-state-background#1]
[When I am in debug mode, the caller package works fine, but when I switch to release mode, it cannot find the caller package. What should I do?

E/flutter (31645): [ERROR:flutter/shell/common/shell.cc(89)] Dart Error: Dart_LookupLibrary: library 'package:phone_state_background/phone_state_background.dart' not found.
E/flutter (31645): [ERROR:flutter/runtime/dart_isolate.cc(668)] Could not resolve main entrypoint function.
E/flutter (31645): [ERROR:flutter/runtime/dart_isolate.cc(168)] Could not run the run main Dart entrypoint.
E/flutter (31645): [ERROR:flutter/runtime/runtime_controller.cc(417)] Could not create root isolate.
E/flutter (31645): [ERROR:flutter/shell/common/shell.cc(606)] Could not launch engine with configuration.

**Comment by sodipto** [comment]
@dongosiddik  What is your flutter sdk version?

**Comment by dongosiddik** [comment]
my  flutter sdk version is  3.7.12

[image: image.png]

Le sam. 6 mai 2023 à 14:30, Sodipto Saha ***@***.***> a
écrit :

**Comment by dongosiddik** [comment]
![image](https://user-images.githubusercontent.com/60137779/236630702-509d8ef6-12a7-4c57-ba32-5f14305daf81.png)

**Comment by dongosiddik** [comment]
@sodipto my  flutter sdk version is  3.7.12
![image](https://user-images.githubusercontent.com/60137779/236630796-608e73a7-94b8-499a-9bf9-9a4eaf032bfd.png)

**Comment by sodipto** [comment]
@dongosiddik I will be check it again. If there is any problem I will let you know right away. Thank you.

**Comment by dongosiddik** [comment]
@sodipto Thank you very much, I'm always listening.

**Comment by sodipto** [comment]
@dongosiddik I fixed this issue. Please use **phone_state_background: ^0.0.3** this version.

@pragma('vm:entry-point') // Be sure to annotate your callback function to avoid issues in release mode.

[See Example](https://pub.dev/packages/phone_state_background/example)

![image](https://user-images.githubusercontent.com/22918946/236637700-80f2869f-d91f-4ade-bb66-bfbd9ba478d2.png)
