### ISSUE TITLE
probleme in mode release

### ISSUE THREAD

**Issue by dongosiddik** [sodipto/flutter-phone-state-background#2]
I still have the same problem. I just installed a new project. I copied your code online to insert into my code on VSCode. I ran 'flutter run --release'. I use android 12

I/flutter (19983): #98     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
I/flutter (19983): #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
I/flutter (19983): Permission true
W/FlutterJNI(19983): FlutterJNI.loadLibrary called more than once
W/FlutterJNI(19983): FlutterJNI.prefetchDefaultFontManager called more than once
W/FlutterJNI(19983): FlutterJNI.init called more than once
W/FlutterJNI(20904): FlutterJNI.loadLibrary called more than once
W/FlutterJNI(20904): FlutterJNI.init called more than once
E/flutter (20904): [ERROR:flutter/shell/common/shell.cc(89)] Dart Error: Dart_LookupLibrary: library 'package:phone_state_background/phone_state_background.dart' not found.
E/flutter (20904): [ERROR:flutter/runtime/dart_isolate.cc(668)] Could not resolve main entrypoint function.
E/flutter (20904): [ERROR:flutter/runtime/dart_isolate.cc(168)] Could not run the run main Dart entrypoint.
E/flutter (20904): [ERROR:flutter/runtime/runtime_controller.cc(417)] Could not create root isolate.
E/flutter (20904): [ERROR:flutter/shell/common/shell.cc(606)] Could not launch engine with configuration.

**Comment by sodipto** [comment]
flutter build apk --release

Use this command for build release apk.

**Comment by sodipto** [comment]
@dongosiddik Before build apk clean this project.

flutter clean

**Comment by dongosiddik** [comment]
@sodipto In fact, I used 'flutter run --release' to directly visualize the release mode on my phone during the development of my app.


![image](https://user-images.githubusercontent.com/60137779/236797639-adbdc25b-8126-4941-a265-bb52c095d668.png)

**Comment by dongosiddik** [comment]
@sodipto Thank you very much, the new version works well but this error message is still present

E/flutter (21832): [ERROR:flutter/shell/common/shell.cc(89)] Dart Error: Dart_LookupLibrary: library 'package:phone_state_background/phone_state_background.dart' not found.
