### ISSUE TITLE
phoneStateBackgroundCallbackHandler; Unhandled Exception: RangeError (length): Invalid value

### ISSUE THREAD

**Issue by dongosiddik** [sodipto/flutter-phone-state-background#3]
@sodipto I often have this problem when I make a call. I don't understand the error.

): Ougoing call start, number: 1800, duration: 0 s
I/flutter ( 2586): Ougoing call ended, number: 1800, duration: 2 s

E/flutter ( 2586): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (length): Invalid value: Only valid value is 0: 1
E/flutter ( 2586): #0      phoneStateBackgroundCallbackHandler (package:eurgencev1/main.dart)
E/flutter ( 2586): <asynchronous suspension>

**Comment by sodipto** [comment]
This error not releted to this plugin.
