### ISSUE TITLE
Outdated version of Kotlin

### ISSUE THREAD

**Issue by SAGARSURI** [sodipto/flutter-phone-state-background#4]
I am getting the following error when using the plugin:
```
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':phone_state_background' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

**Comment by sodipto** [comment]
@SAGARSURI can share  your flutter sdk version and kotlin version?

**Comment by SAGARSURI** [comment]
Kotlin: 1.7.10
Flutter: 3.10.1

**Comment by sodipto** [comment]
@SAGARSURI Please update your flutter sdk version.

**Comment by SAGARSURI** [comment]
But that's the latest Flutter version @sodipto . Which version are you using?

**Comment by sodipto** [comment]
@SAGARSURI Use 3.7.0 flutter sdk version.

**Comment by SAGARSURI** [comment]
That's old version @sodipto . Please check flutter version page:
https://docs.flutter.dev/release/release-notes

**Comment by sodipto** [comment]
@SAGARSURI see this article

https://stackoverflow.com/questions/54693595/flutter-the-android-gradle-plugin-supports-only-kotlin-gradle-plugin-version-1

Android gradle plugin issue.

**Comment by sodipto** [comment]
> That's old version @sodipto . Please check flutter version page:
> https://docs.flutter.dev/release/release-notes

Many users, including me using this sdk version and this plugin, work perfectly.

**Comment by SAGARSURI** [comment]
You need to upgrade your gradle version:
```
buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```
Then only you can upgrade to latest kotlin version. But anyway I will create my own plugin. Thanks 😄

**Comment by SAGARSURI** [comment]
Your `build.gradle` is using a very old version of gradle:
```
classpath 'com.android.tools.build:gradle:4.1.0'
```
