### ISSUE TITLE
No implementation found for method hasPermission on channel

### ISSUE THREAD

**Issue by fayaman99** [sodipto/flutter-phone-state-background#5]
test() async {
  try {
    await audioRecorder.hasPermission();
  } catch (e) {
    print(e);
  }
}

Future<void> phoneStateBackgroundCallbackHandler(
  PhoneStateBackgroundEvent event,
  String number,
  int duration,
) async {
  switch (event) {
    case PhoneStateBackgroundEvent.incomingstart:
      test();
      print("telephone sonne appel entrant");
      break;
    case PhoneStateBackgroundEvent.incomingmissed:
      //
      break;
    case PhoneStateBackgroundEvent.incomingreceived:
      // 
      break;
    case PhoneStateBackgroundEvent.incomingend:
      // 
      print("Appel terminé");
      break;
    case PhoneStateBackgroundEvent.outgoingstart:
      //
      break;
    case PhoneStateBackgroundEvent.outgoingend:
      // 
      break;
  }
}

Future<void> Lencement_appel() async {
  test(bool); // return true
  final permission = await PhoneStateBackground.checkPermission();
  if (permission != true) return;
  await PhoneStateBackground.initialize(phoneStateBackgroundCallbackHandler);
}

//********* error ********** //

I/flutter ( 4489): MissingPluginException(No implementation found for method hasPermission on channel com.llfbandit.record/messages)

**Comment by sodipto** [comment]
@fayaman99 this issue may b your **audio recoder** permission issue. Please cross check.

**Comment by fayaman99** [comment]
I have already obtained all the authorization on my main.dart,  I can make audio recordings before the phone rings, when the phone rings, it returns this error

//******* main.dart ******//

Future<void> getAllPermission() async {
    await PhoneStateBackground.requestPermissions();
    Map<Permission, PermissionStatus> statuses = await [
      Permission.location,
      Permission.microphone,
      Permission.sms,
      Permission.phone,
      Permission.contacts,
      Permission.storage
    ].request();
    // await MesVariableGlobal.telephony.requestPhoneAndSmsPermissions;
  }

**Comment by sodipto** [comment]
@fayaman99  Make sure this two permission added your mainfest file and also checked your app permissions.

```
<uses-permission android:name="android.permission.READ_PHONE_STATE" />
<uses-permission android:name="android.permission.READ_CALL_LOG" />
```

**Comment by fayaman99** [comment]
I already have this in my AndroidManifest.xml but it doesn't work

**Comment by sodipto** [comment]
![image](https://github.com/sodipto/flutter-phone-state-background/assets/22918946/d43616b8-49e1-48b2-982d-015613824620)

Use like this.

**Comment by sodipto** [comment]
Also clean your project and rebuild and run again.

**Comment by fayaman99** [comment]
I tried, but it doesn't work

**Comment by sodipto** [comment]
Provide your Flutter sdk version and kotlin version.

**Comment by sodipto** [comment]
![image](https://github.com/sodipto/flutter-phone-state-background/assets/22918946/2359346a-a032-4642-85e0-77ef25555730)

Please check this. Error occur audio plugin. Check my plugin separate project without audio plugin.

**Comment by sodipto** [comment]
Also provide your app permission settings screen?

**Comment by fayaman99** [comment]
![Capture d’écran (20)](https://github.com/sodipto/flutter-phone-state-background/assets/122408694/ed2716c3-9354-4a8c-8e8d-bb4d6ceba143)
![Capture d’écran (21)](https://github.com/sodipto/flutter-phone-state-background/assets/122408694/3da4846b-349d-40e4-b5b7-9347b7d98d58)
![Capture d’écran (22)](https://github.com/sodipto/flutter-phone-state-background/assets/122408694/c9325cbf-6b46-4ed4-a267-3e0c90bdf209)

**Comment by sodipto** [comment]
https://meet.google.com/ksv-zztn-ibt please join this link if possiable

**Comment by sodipto** [comment]
Try to Create new project and run.
