### ISSUE TITLE
READ_CALL_LOG opt out

### ISSUE THREAD

**Issue by nt4f04uNd** [sodipto/flutter-phone-state-background#8]
Hey, thanks for making this plugin, it will come handy in one of my projects!

I have a suggestion which would make the plugin even better.

### Problem

I want to trigger my code on incoming call and I don't need to see the number.

Currently the plugin forces me to declare `android.permission.READ_CALL_LOG` permission, which would be excessive for my app's functionality and would cause an obvious mistrust from the user's side. 

### Solution

Allow to use plugin to use without `android.permission.READ_CALL_LOG`, making its declaration optional.

**Comment by sodipto** [comment]
@nt4f04uNd Without READ_CALL_LOG permission this plugin not working. Please read android TELEPHONY MANAGER for better understand. Thanks
